namespace: dev-test
replicaCount: 1
image:
  repository: charlilyyyy/test-be
  tag: "latest"
  pullPolicy: IfNotPresent
containerPort: 27017
service:
  type: ClusterIP
  port: 27017
ingress:
  enabled: false
  className: ""
  annotations: {}
  # hosts:
  #   - host: fastapi.example.com
  #     paths:
  #       - path: /
  #         pathType: Prefix
  tls: []
nodeSelector:
  kubernetes.io/hostname: minikube
tolerations: []
affinity: {}
# imagePullSecrets:
#   - name: acr-creds

# Configuration values
config:
  environment: "development"
  logLevel: "INFO"
  corsOrigins: "http://localhost:5173,http://localhost:3000"
  apiVersion: "v1"
  debug: "true"