{{- if .Values.datasources.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-datasources
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "grafana-chart.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    {{- range .Values.datasources.datasources }}
    - name: {{ .name }}
      type: {{ .type }}
      url: {{ .url }}
      access: {{ .access }}
      isDefault: {{ .isDefault }}
      editable: true
    {{- end }}
{{- end }}

