# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: {{ .Release.Name }}-keyvault-secret-provider
#   namespace: {{ .Values.namespace }}
#   labels:
#     {{- include "backend-chart.labels" . | nindent 4 }}
# spec:
#   provider: azure
#   parameters:
#     usePodIdentity: "false"
#     useVMManagedIdentity: "false"
#     userAssignedIdentityID: {{ .Values.keyVault.userAssignedIdentityID | quote }}
#     keyvaultName: {{ .Values.keyVault.vaultName | quote }}
#     tenantId: {{ .Values.keyVault.tenantId | quote }}
#     objects: |
#       array:
#         - |
#           objectName: {{ .Values.keyVault.secrets.apiToken.name | quote }}
#           objectType: secret
#           objectVersion: {{ .Values.keyVault.secrets.apiToken.version | quote }}
#         - |
#           objectName: {{ .Values.keyVault.secrets.databasePassword.name | quote }}
#           objectType: secret
#           objectVersion: {{ .Values.keyVault.secrets.databasePassword.version | quote }}
#         - |
#           objectName: {{ .Values.keyVault.secrets.jwtSecret.name | quote }}
#           objectType: secret
#           objectVersion: {{ .Values.keyVault.secrets.jwtSecret.version | quote }}
#     secretObjects:
#       - secretName: {{ .Release.Name }}-secrets
#         type: Opaque
#         data:
#           - objectName: {{ .Values.keyVault.secrets.apiToken.name | quote }}
#             key: API_TOKEN
#           - objectName: {{ .Values.keyVault.secrets.databasePassword.name | quote }}
#             key: DATABASE_PASSWORD
#           - objectName: {{ .Values.keyVault.secrets.jwtSecret.name | quote }}
#             key: JWT_SECRET
