apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      containers:
        - name: backend
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
          env:
            - name: PG_HOST
              value: {{ .Values.env.pgHost | default "postgres" }}
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.pgSecretName | default "pg-secret" }}
                  key: POSTGRES_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.pgSecretName | default "pg-secret" }}
                  key: POSTGRES_PASSWORD
            - name: PG_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.pgSecretName | default "pg-secret" }}
                  key: POSTGRES_DB
            - name: NEO4J_URI
              value: {{ .Values.env.neo4jUri | default "bolt://neo4j:7687" }}
            - name: NEO4J_USER
              value: {{ .Values.env.neo4jUser | default "neo4j" }}
            - name: NEO4J_PASSWORD
              value: {{ .Values.env.neo4jPassword | default "example" }}

            # - secretRef:
            #     name: {{ .Release.Name }}-secrets
          # volumeMounts:
          #   - name: secrets-store
          #     mountPath: "/mnt/secrets-store"
          #     readOnly: true
      # volumes:
      #   - name: secrets-store
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: {{ .Release.Name }}-keyvault-secret-provider
