# Development environment values
namespace: dev-test
replicaCount: 1
image:
  repository: charlilyyyy/test-fe
  tag: "latest"  # or "latest" for dev
containerPort: 80
ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  # hosts:
  #   - host: dev.example.com
  #     paths:
  #       - path: /
  #         pathType: Prefix
  tls: []
service:
  type: ClusterIP
  port: 80
# Scheduling - prefer minikube but allow fallback to other nodes
nodeSelector: {}
tolerations: []
affinity:
  # Prefer minikube node but allow fallback to other nodes
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      preference:
        matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
          - linux
  # Anti-affinity to spread pods across nodes when possible
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 50
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - frontend-chart
        topologyKey: kubernetes.io/hostname
# imagePullSecrets:
#   - name: acr-creds

# Configuration values
config:
  apiBaseUrl: "/api"
  environment: "development"
  version: "1.0.0"
  debug: "true"